workflows:
  android-workflow:
    name: Android Capacitor Build
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web App
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew      
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk